### ISSUE TITLE
usernames do not permit single-character users or domains

### ISSUE THREAD

**Issue by rogpeppe** [juju/names#54]
For instance, Rob Pike's user name (r@google) would be disallowed.
This seems like an unnecessary restriction which is easily lifted.

**Comment by anastasiamac** [comment]
I've created a launchpad issue for consideration - Juju uses names package extensively. Juju needs should be considered when making this change.

https://bugs.launchpad.net/juju/+bug/1620444

**Comment by anastasiamac** [comment]
Since we are tracking our issues through launchpad, I am closing the issues on github.
Please use the above link for the bug \o/
